allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/vite-plugin@1.42.1'
  - '@cloudflare/vitest-pool-workers@0.16.18'
  - '@tanstack/devtools-client@0.0.7'
  - '@tanstack/devtools-event-bus@0.4.2'
  - '@tanstack/devtools-event-client@0.4.4'
  - '@tanstack/devtools-ui@0.5.3'
  - '@tanstack/devtools-vite@0.8.0'
  - '@tanstack/devtools@0.12.4'
  - '@tanstack/react-devtools@0.10.7'
  - '@types/node@26.0.0'
  - miniflare@4.20260617.1
  - wrangler@4.103.0
