allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@tanstack/react-router@1.170.15'
  - '@tanstack/react-start-client@1.168.12'
  - '@tanstack/react-start-rsc@0.1.23'
  - '@tanstack/react-start-server@1.167.18'
  - '@tanstack/react-start@1.168.24'
  - '@tanstack/router-core@1.171.13'
  - '@tanstack/router-generator@1.167.17'
  - '@tanstack/router-plugin@1.168.18'
  - '@tanstack/router-utils@1.162.2'
  - '@tanstack/start-client-core@1.170.11'
  - '@tanstack/start-plugin-core@1.171.16'
  - '@tanstack/start-server-core@1.169.13'
  - '@tanstack/start-storage-context@1.167.15'
  - '@types/node@25.9.2'
  - '@types/react@19.2.17'
